name: CI Process
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  behave-testing:
    runs-on: ubuntu-latest  #setup OS of choice

    permissions:
      issues: write
      checks: write
      pull-requests: write  
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List repo
        run: |
          ls
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'
      - name: install pip
        run: |
          python -m pip install --upgrade pip
          pip install behave
      - name: run bahave test
        run: |
          behave features/ --junit --junit-directory=test-results
      - name: upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            test-results/**/*.xml
            test-results/*.xml


          

