name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest  #setup OS of choice
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - name: List repo
      - run: |
          ls

